import React, { useState, useEffect, useRef } from 'react';
import {
  Clock,
  Play,
  Pause,
  ChevronLeft,
  ChevronRight,
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  FileSearch,
  ExternalLink,
  Info,
  Copy,
  Check,
  FastForward,
  RotateCcw,
  Zap,
} from 'lucide-react';
import { AttackChainStep, RawAiAnalysis, TimelineEvent } from '../types/analysis';
import { buildScamTimeline } from '../lib/timeline/timeline-generator';

interface ScamTimelineProps {
  steps: AttackChainStep[];
  rawAnalysis?: RawAiAnalysis;
}

export const ScamTimeline: React.FC<ScamTimelineProps> = ({ steps, rawAnalysis }) => {
  const { events, currentEventIndex, interventionIndex } = buildScamTimeline(steps, rawAnalysis);

  // Active selected event index
  const [selectedIndex, setSelectedIndex] = useState<number>(() => {
    // Default to the first detected/observed event or index 0
    return currentEventIndex >= 0 ? currentEventIndex : 0;
  });

  // Filter mode: 'all' | 'observed' | 'projected'
  const [filterMode, setFilterMode] = useState<'all' | 'observed' | 'projected'>('all');

  // View mode: 'interactive' | 'matrix'
  const [viewMode, setViewMode] = useState<'interactive' | 'matrix'>('interactive');

  // Auto-play simulation state
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [playbackSpeed, setPlaybackSpeed] = useState<number>(1); // 1x or 2x
  const [copiedTimeline, setCopiedTimeline] = useState<boolean>(false);

  // Scenario toggle: 'comply' vs 'intervene'
  const [scenarioMode, setScenarioMode] = useState<'intervene' | 'comply'>('intervene');

  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Filtered list of events
  const filteredEvents = events.filter((ev) => {
    if (filterMode === 'observed') return ev.isObserved;
    if (filterMode === 'projected') return !ev.isObserved;
    return true;
  });

  // Keep selectedIndex valid within filteredEvents
  const activeEvent = filteredEvents.find((_, idx) => idx === selectedIndex) || filteredEvents[0] || events[0];

  // Auto-play simulation loop
  useEffect(() => {
    if (isPlaying) {
      const intervalMs = 2800 / playbackSpeed;
      timerRef.current = setInterval(() => {
        setSelectedIndex((prev) => {
          if (prev >= filteredEvents.length - 1) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, intervalMs);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [isPlaying, playbackSpeed, filteredEvents.length]);

  const handleNext = () => {
    if (selectedIndex < filteredEvents.length - 1) {
      setSelectedIndex(selectedIndex + 1);
    }
  };

  const handlePrev = () => {
    if (selectedIndex > 0) {
      setSelectedIndex(selectedIndex - 1);
    }
  };

  const handleResetPlayback = () => {
    setIsPlaying(false);
    setSelectedIndex(0);
  };

  const handleJumpToCurrent = () => {
    const targetIdx = filteredEvents.findIndex((ev) => ev.id === events[currentEventIndex]?.id);
    if (targetIdx !== -1) {
      setSelectedIndex(targetIdx);
    }
  };

  const handleCopyTimelineSummary = () => {
    const lines = [
      'SCAMTRACE CHRONOLOGICAL THREAT TIMELINE',
      '========================================',
      ...events.map(
        (ev, i) =>
          `[${ev.timeLabel}] ${ev.title} (${ev.isObserved ? 'OBSERVED IN OFFER' : 'PROJECTED ESCALATION'})\n` +
          `  - Tactic: ${ev.adversaryTactic}\n` +
          `  - Evidence: ${ev.evidence}\n` +
          `  - Immediate Countermeasure: ${ev.killChainAction}\n`
      ),
      '========================================',
      'Generated by SCAMTRACE Forensics Engine',
    ];
    navigator.clipboard.writeText(lines.join('\n'));
    setCopiedTimeline(true);
    setTimeout(() => setCopiedTimeline(false), 2000);
  };

  if (!events || events.length === 0) {
    return null;
  }

  // Get color accents by stage / severity
  const getStageAccent = (ev: TimelineEvent) => {
    if (ev.stage === 'financial' || ev.stage === 'extortion') {
      return {
        border: 'border-rose-500/40',
        bg: 'bg-rose-950/20',
        text: 'text-rose-400',
        dot: 'bg-rose-500',
        ring: 'ring-rose-500/30',
        badgeBg: 'bg-rose-950/50 border-rose-500/30 text-rose-300',
      };
    }
    if (ev.stage === 'urgency') {
      return {
        border: 'border-amber-500/40',
        bg: 'bg-amber-950/20',
        text: 'text-amber-400',
        dot: 'bg-amber-500',
        ring: 'ring-amber-500/30',
        badgeBg: 'bg-amber-950/50 border-amber-500/30 text-amber-300',
      };
    }
    if (ev.stage === 'data' || ev.stage === 'credential') {
      return {
        border: 'border-purple-500/40',
        bg: 'bg-purple-950/20',
        text: 'text-purple-400',
        dot: 'bg-purple-500',
        ring: 'ring-purple-500/30',
        badgeBg: 'bg-purple-950/50 border-purple-500/30 text-purple-300',
      };
    }
    return {
      border: 'border-cyan-500/40',
      bg: 'bg-cyan-950/20',
      text: 'text-cyan-400',
      dot: 'bg-cyan-500',
      ring: 'ring-cyan-500/30',
      badgeBg: 'bg-cyan-950/50 border-cyan-500/30 text-cyan-300',
    };
  };

  const activeAccent = getStageAccent(activeEvent);

  return (
    <div id="scam-timeline-section" className="w-full max-w-4xl mx-auto px-4 mb-8">
      {/* Section Header with Actions */}
      <div className="mb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg bg-cyan-950/60 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <Clock className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white tracking-tight">
                Scam Timeline
              </h3>
              <span className="text-[11px] font-mono text-cyan-400 px-1.5 py-0.5 rounded bg-cyan-950/40 border border-cyan-800/40">
                Chronological Projection
              </span>
            </div>
            <p className="text-xs text-slate-400">
              Interactive timeline mapping detected events and theoretical attack escalation
            </p>
          </div>
        </div>

        {/* Top Control Bar */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          {/* View Toggle (Interactive vs Matrix) */}
          <div className="flex items-center p-0.5 bg-slate-900 border border-slate-800 rounded-lg text-xs">
            <button
              type="button"
              onClick={() => setViewMode('interactive')}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                viewMode === 'interactive'
                  ? 'bg-cyan-950 text-cyan-300 border border-cyan-800/50'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Timeline View
            </button>
            <button
              type="button"
              onClick={() => setViewMode('matrix')}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                viewMode === 'matrix'
                  ? 'bg-cyan-950 text-cyan-300 border border-cyan-800/50'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Sequence Flow
            </button>
          </div>

          {/* Copy Report */}
          <button
            type="button"
            onClick={handleCopyTimelineSummary}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-slate-800 bg-slate-900 text-xs font-mono text-slate-300 hover:text-cyan-300 hover:border-slate-700 transition-colors"
            title="Copy Chronological Timeline"
          >
            {copiedTimeline ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-[11px] text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span className="text-[11px] hidden sm:inline">Export</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Container Card */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:p-5 shadow-xl backdrop-blur-sm">
        {/* Sub-header: Playback Controls & Filter Tabs */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 mb-4 border-b border-slate-800/70">
          {/* Simulation & Playback Controls */}
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setIsPlaying(!isPlaying)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium font-mono transition-all ${
                isPlaying
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 hover:bg-amber-500/30'
                  : 'bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 hover:bg-cyan-500/20 shadow-sm'
              }`}
            >
              {isPlaying ? (
                <>
                  <Pause className="w-3.5 h-3.5 fill-current" />
                  <span>Pause Simulation</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-current" />
                  <span>Auto-Simulate</span>
                </>
              )}
            </button>

            {/* Stepper buttons */}
            <div className="flex items-center bg-slate-950 border border-slate-800 rounded-lg p-0.5">
              <button
                type="button"
                onClick={handlePrev}
                disabled={selectedIndex === 0}
                className="p-1 rounded text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                title="Previous Milestone"
                aria-label="Previous milestone"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-[11px] font-mono px-2 text-slate-400">
                {selectedIndex + 1}/{filteredEvents.length}
              </span>
              <button
                type="button"
                onClick={handleNext}
                disabled={selectedIndex === filteredEvents.length - 1}
                className="p-1 rounded text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                title="Next Milestone"
                aria-label="Next milestone"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>

            {/* Speed Toggle */}
            <button
              type="button"
              onClick={() => setPlaybackSpeed(playbackSpeed === 1 ? 2 : 1)}
              className="px-2 py-1 rounded border border-slate-800 bg-slate-950 text-[11px] font-mono text-slate-400 hover:text-slate-200 transition-colors"
              title="Toggle Playback Speed"
            >
              {playbackSpeed}x
            </button>

            {/* Reset */}
            <button
              type="button"
              onClick={handleResetPlayback}
              className="p-1.5 rounded border border-slate-800 bg-slate-950 text-slate-400 hover:text-slate-200 transition-colors"
              title="Reset to Beginning"
              aria-label="Reset simulation"
            >
              <RotateCcw className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Filter Pills (All / Observed / Projected) */}
          <div className="flex items-center p-0.5 bg-slate-950 border border-slate-800 rounded-lg text-xs self-start sm:self-auto">
            <button
              type="button"
              onClick={() => {
                setFilterMode('all');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'all'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              All Events ({events.length})
            </button>
            <button
              type="button"
              onClick={() => {
                setFilterMode('observed');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'observed'
                  ? 'bg-emerald-950/80 text-emerald-300 border border-emerald-800/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Observed ({events.filter((e) => e.isObserved).length})
            </button>
            <button
              type="button"
              onClick={() => {
                setFilterMode('projected');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'projected'
                  ? 'bg-cyan-950/80 text-cyan-300 border border-cyan-800/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Projected ({events.filter((e) => !e.isObserved).length})
            </button>
          </div>
        </div>

        {/* View Mode 1: Interactive Timeline Track & Inspector Card */}
        {viewMode === 'interactive' && (
          <div>
            {/* Interactive Chronological Spine / Node Scrubber */}
            <div className="relative pt-6 pb-8 px-2 overflow-x-auto">
              {/* Horizontal Line background */}
              <div className="absolute top-10 left-6 right-6 h-0.5 bg-slate-800 -translate-y-1/2" />

              {/* Dynamic filled line up to active node */}
              {filteredEvents.length > 1 && (
                <div
                  className="absolute top-10 left-6 h-0.5 bg-gradient-to-r from-cyan-500 via-amber-500 to-rose-500 -translate-y-1/2 transition-all duration-300"
                  style={{
                    width: `calc(${(selectedIndex / (filteredEvents.length - 1)) * 100}% - 24px)`,
                  }}
                />
              )}

              {/* Node Points along the spine */}
              <div className="relative flex items-center justify-between min-w-[560px]">
                {filteredEvents.map((ev, idx) => {
                  const isSelected = idx === selectedIndex;
                  const isCurrentPosition = ev.id === events[currentEventIndex]?.id;
                  const isInterventionLine = idx === interventionIndex;
                  const accent = getStageAccent(ev);

                  return (
                    <div key={ev.id} className="flex flex-col items-center group relative">
                      {/* "You Are Here" Marker */}
                      {isCurrentPosition && (
                        <div className="absolute -top-7 flex flex-col items-center animate-bounce">
                          <span className="text-[10px] font-mono font-bold text-amber-400 px-1.5 py-0.2 rounded bg-amber-950 border border-amber-800/60 whitespace-nowrap shadow-sm">
                            YOU ARE HERE
                          </span>
                          <div className="w-1.5 h-1.5 bg-amber-400 rotate-45 -mt-0.5" />
                        </div>
                      )}

                      {/* Node Button */}
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedIndex(idx);
                          setIsPlaying(false);
                        }}
                        className={`w-8 h-8 rounded-full flex items-center justify-center transition-all cursor-pointer relative z-10 ${
                          isSelected
                            ? `bg-slate-950 border-2 ${accent.border} ring-4 ${accent.ring} scale-110 shadow-lg`
                            : 'bg-slate-900 border border-slate-700 hover:border-slate-500 hover:scale-105'
                        }`}
                        title={`${ev.timeLabel}: ${ev.title}`}
                      >
                        <span
                          className={`w-2.5 h-2.5 rounded-full ${
                            ev.isObserved ? accent.dot : 'bg-slate-500'
                          } ${isSelected ? 'animate-pulse' : ''}`}
                        />
                      </button>

                      {/* Time Marker Label */}
                      <div className="mt-2 text-center">
                        <span
                          className={`block text-[11px] font-mono font-bold ${
                            isSelected ? 'text-cyan-300' : 'text-slate-400'
                          }`}
                        >
                          {ev.timeLabel}
                        </span>
                        <span
                          className={`block text-[10px] max-w-[80px] truncate leading-tight mt-0.5 ${
                            isSelected ? 'text-slate-200 font-semibold' : 'text-slate-500'
                          }`}
                        >
                          {ev.title}
                        </span>
                      </div>

                      {/* Intervention Cut-off Line Indicator */}
                      {isInterventionLine && (
                        <div
                          className="absolute -bottom-5 text-[9px] font-mono text-rose-400 whitespace-nowrap"
                          title="Point of No Return: Cease all actions before this milestone"
                        >
                          ⚠ Critical Cut-Off
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Active Milestone Forensic Detail Card */}
            <div
              className={`rounded-xl border ${activeAccent.border} ${activeAccent.bg} p-4 sm:p-6 transition-all duration-300 mt-2`}
            >
              {/* Card Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 pb-3 border-b border-slate-800/80">
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-xs font-mono font-bold tracking-wider text-cyan-400">
                      {activeEvent.timeframe}
                    </span>
                    <span className="text-slate-600">·</span>
                    <span
                      className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${
                        activeEvent.isObserved
                          ? 'bg-emerald-950/60 text-emerald-300 border-emerald-700/50'
                          : 'bg-slate-900 text-slate-400 border-slate-700/60'
                      }`}
                    >
                      {activeEvent.isObserved ? 'OBSERVED IN OFFER' : 'PROJECTED THREAT'}
                    </span>
                    <span className="text-slate-600">·</span>
                    <span className="text-[10px] font-mono uppercase text-slate-400">
                      Stage: {activeEvent.stage}
                    </span>
                  </div>
                  <h4 className="text-base sm:text-lg font-bold text-white tracking-tight">
                    {activeEvent.title}
                  </h4>
                </div>

                {/* Jump to 'You Are Here' if not already on it */}
                {events[currentEventIndex] && activeEvent.id !== events[currentEventIndex]?.id && (
                  <button
                    type="button"
                    onClick={handleJumpToCurrent}
                    className="self-start sm:self-auto text-xs font-mono text-amber-300 hover:text-amber-200 px-2.5 py-1 rounded bg-amber-950/40 border border-amber-800/50 transition-colors"
                  >
                    Jump to Current State →
                  </button>
                )}
              </div>

              {/* 4-Quadrant Information Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-4">
                {/* Quadrant 1: Evidence / Verbatim Text */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                      <FileSearch className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Observed Artifact & Signal</span>
                    </span>
                    {activeEvent.isObserved && (
                      <span className="text-[10px] font-mono text-emerald-400 bg-emerald-950/40 px-1.5 py-0.5 rounded border border-emerald-800/40">
                        Direct Evidence
                      </span>
                    )}
                  </div>
                  <div className="text-xs font-mono text-slate-300 bg-slate-900/90 rounded p-2.5 border border-slate-800/60 italic leading-relaxed">
                    "{activeEvent.evidence}"
                  </div>
                  <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                    {activeEvent.explanation}
                  </p>
                </div>

                {/* Quadrant 2: Adversary Playbook & Tactic */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <Zap className="w-3.5 h-3.5 text-amber-400" />
                    <span className="text-xs font-semibold text-slate-300">
                      Adversary Playbook & Tactic
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed mb-3">
                    {activeEvent.adversaryTactic}
                  </p>
                  <div className="pt-2 border-t border-slate-800/60">
                    <span className="text-[11px] font-mono text-slate-400 block mb-0.5">
                      Psychological Lever:
                    </span>
                    <span className="text-xs font-medium text-amber-300/90">
                      {activeEvent.psychologicalLever}
                    </span>
                  </div>
                </div>

                {/* Quadrant 3: Potential Victim Exposure */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <AlertTriangle className="w-3.5 h-3.5 text-rose-400" />
                    <span className="text-xs font-semibold text-slate-300">
                      Victim Impact at this Milestone
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed mb-2">
                    {activeEvent.potentialVictimImpact}
                  </p>
                  <div className="text-[11px] font-mono text-rose-300/80 bg-rose-950/30 p-2 rounded border border-rose-900/40">
                    <span className="font-semibold text-rose-400">If ignored: </span>
                    {activeEvent.consequenceIfIgnored}
                  </div>
                </div>

                {/* Quadrant 4: Immediate Kill-Chain Countermeasure */}
                <div className="rounded-lg bg-cyan-950/40 border border-cyan-800/50 p-3.5 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-1.5 mb-2">
                      <ShieldAlert className="w-3.5 h-3.5 text-cyan-400" />
                      <span className="text-xs font-bold text-cyan-300 uppercase tracking-wide">
                        Kill-Chain Break Window
                      </span>
                    </div>
                    <p className="text-xs font-medium text-cyan-100 leading-relaxed">
                      {activeEvent.killChainAction}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-cyan-800/40 flex items-center justify-between text-[11px] font-mono text-cyan-300/80">
                    <span>Defuse Risk:</span>
                    <span className="text-emerald-400 font-bold">100% Effective</span>
                  </div>
                </div>
              </div>

              {/* Interactive "What-If" Scenario Branching */}
              <div className="mt-4 pt-3 border-t border-slate-800/70">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                  <span className="text-xs font-mono font-bold text-slate-300 flex items-center gap-1.5">
                    <span>What-If Tactical Branching:</span>
                  </span>
                  <div className="flex items-center p-0.5 bg-slate-950 border border-slate-800 rounded-md text-xs self-start sm:self-auto">
                    <button
                      type="button"
                      onClick={() => setScenarioMode('intervene')}
                      className={`px-2.5 py-1 rounded font-medium transition-colors ${
                        scenarioMode === 'intervene'
                          ? 'bg-emerald-950 text-emerald-300 border border-emerald-700/50'
                          : 'text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      Branch A: Candidate Intervenes (Safe)
                    </button>
                    <button
                      type="button"
                      onClick={() => setScenarioMode('comply')}
                      className={`px-2.5 py-1 rounded font-medium transition-colors ${
                        scenarioMode === 'comply'
                          ? 'bg-rose-950 text-rose-300 border border-rose-700/50'
                          : 'text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      Branch B: Candidate Complies (Loss)
                    </button>
                  </div>
                </div>

                <div
                  className={`rounded-lg p-3 text-xs leading-relaxed border ${
                    scenarioMode === 'intervene'
                      ? 'bg-emerald-950/20 border-emerald-800/40 text-emerald-200'
                      : 'bg-rose-950/20 border-rose-800/40 text-rose-200'
                  }`}
                >
                  {scenarioMode === 'intervene' ? (
                    <div className="flex items-start gap-2">
                      <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-emerald-300 block mb-0.5">
                          Protective Outcome:
                        </strong>
                        When you request independent confirmation through the official corporate
                        directory or refuse upfront payment, the adversary fails. They will either
                        evade live verification, terminate the chat, or reveal conflicting domains.
                        Your financial loss and identity exposure remain $0.
                      </div>
                    </div>
                  ) : (
                    <div className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-rose-300 block mb-0.5">
                          Adversary Escalation Trajectory:
                        </strong>
                        Complying at {activeEvent.timeLabel} signals to the scam syndicate that you
                        are a receptive target. They proceed immediately to the next phase (
                        {events[Math.min(selectedIndex + 1, events.length - 1)]?.title}), demanding
                        secondary verification deposits or harvesting banking credentials.
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* View Mode 2: Full Sequence Matrix / Flow Grid */}
        {viewMode === 'matrix' && (
          <div className="space-y-3 pt-2">
            <div className="text-xs text-slate-400 mb-2 flex items-center justify-between">
              <span>Full chronological trajectory from initial hook to post-incident exploitation:</span>
              <span className="font-mono text-cyan-400">Total Milestones: {filteredEvents.length}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {filteredEvents.map((ev, idx) => {
                const accent = getStageAccent(ev);
                const isCurrentPosition = ev.id === events[currentEventIndex]?.id;

                return (
                  <div
                    key={ev.id}
                    className={`rounded-xl border p-4 transition-all ${
                      isCurrentPosition
                        ? 'border-amber-500/50 bg-amber-950/10 ring-2 ring-amber-500/20'
                        : 'border-slate-800 bg-slate-950/60 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono font-bold text-cyan-400">
                          {ev.timeLabel}
                        </span>
                        <span className="text-slate-600">·</span>
                        <span className="text-[11px] font-mono text-slate-400">
                          {ev.timeframe}
                        </span>
                      </div>
                      <span
                        className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
                          ev.isObserved
                            ? 'bg-emerald-950/60 text-emerald-300 border-emerald-800/40'
                            : 'bg-slate-900 text-slate-400 border-slate-800'
                        }`}
                      >
                        {ev.isObserved ? 'OBSERVED' : 'PROJECTED'}
                      </span>
                    </div>

                    <h4 className="text-sm font-semibold text-white mb-2">{ev.title}</h4>

                    <div className="p-2 rounded bg-slate-900/80 border border-slate-800/60 text-xs font-mono text-slate-300 italic mb-2 line-clamp-2">
                      "{ev.evidence}"
                    </div>

                    <p className="text-xs text-slate-400 mb-2.5 line-clamp-2">
                      {ev.explanation}
                    </p>

                    <div className="pt-2 border-t border-slate-800/60 flex items-center justify-between text-[11px]">
                      <span className="text-slate-400 font-mono">Countermeasure:</span>
                      <span className="text-cyan-300 font-medium truncate max-w-[200px]" title={ev.killChainAction}>
                        {ev.killChainAction}
                      </span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
