import React, { useState, useEffect, useRef } from 'react';
import {
  Clock,
  Play,
  Pause,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  FileSearch,
  ExternalLink,
  Info,
  Copy,
  Check,
  FastForward,
  RotateCcw,
  Zap,
  UserCheck,
  CreditCard,
  FileSpreadsheet,
  Key,
  AlertOctagon,
  UserX,
} from 'lucide-react';
import { AttackChainStep, RawAiAnalysis, TimelineEvent } from '../types/analysis';
import { buildScamTimeline } from '../lib/timeline/timeline-generator';

interface ScamTimelineProps {
  steps: AttackChainStep[];
  rawAnalysis?: RawAiAnalysis;
}

export const ScamTimeline: React.FC<ScamTimelineProps> = ({ steps, rawAnalysis }) => {
  const { events, currentEventIndex, interventionIndex } = buildScamTimeline(steps, rawAnalysis);

  // Active selected event index
  const [selectedIndex, setSelectedIndex] = useState<number>(() => {
    // Default to the first detected/observed event or index 0
    return currentEventIndex >= 0 ? currentEventIndex : 0;
  });

  // Filter mode: 'all' | 'observed' | 'projected'
  const [filterMode, setFilterMode] = useState<'all' | 'observed' | 'projected'>('all');

  // View mode: 'interactive' | 'matrix'
  const [viewMode, setViewMode] = useState<'interactive' | 'matrix'>('interactive');

  // Auto-play simulation state
  const [isPlaying, setIsPlaying] = useState<boolean>(false);
  const [playbackSpeed, setPlaybackSpeed] = useState<number>(1); // 1x or 2x
  const [copiedTimeline, setCopiedTimeline] = useState<boolean>(false);

  // Scenario toggle: 'comply' vs 'intervene'
  const [scenarioMode, setScenarioMode] = useState<'intervene' | 'comply'>('intervene');

  // Prevention tips state
  const [isPreventionTipsExpanded, setIsPreventionTipsExpanded] = useState<boolean>(true);
  const [matrixExpandedTips, setMatrixExpandedTips] = useState<Record<string, boolean>>({});
  const [copiedTipsStageId, setCopiedTipsStageId] = useState<string | null>(null);

  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Filtered list of events
  const filteredEvents = events.filter((ev) => {
    if (filterMode === 'observed') return ev.isObserved;
    if (filterMode === 'projected') return !ev.isObserved;
    return true;
  });

  // Keep selectedIndex valid within filteredEvents
  const activeEvent = filteredEvents.find((_, idx) => idx === selectedIndex) || filteredEvents[0] || events[0];

  // Auto-play simulation loop
  useEffect(() => {
    if (isPlaying) {
      const intervalMs = 2800 / playbackSpeed;
      timerRef.current = setInterval(() => {
        setSelectedIndex((prev) => {
          if (prev >= filteredEvents.length - 1) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, intervalMs);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }

    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [isPlaying, playbackSpeed, filteredEvents.length]);

  const handleNext = () => {
    if (selectedIndex < filteredEvents.length - 1) {
      setSelectedIndex(selectedIndex + 1);
    }
  };

  const handlePrev = () => {
    if (selectedIndex > 0) {
      setSelectedIndex(selectedIndex - 1);
    }
  };

  const handleResetPlayback = () => {
    setIsPlaying(false);
    setSelectedIndex(0);
  };

  const handleJumpToCurrent = () => {
    const targetIdx = filteredEvents.findIndex((ev) => ev.id === events[currentEventIndex]?.id);
    if (targetIdx !== -1) {
      setSelectedIndex(targetIdx);
    }
  };

  const handleCopyTimelineSummary = () => {
    const lines = [
      'SCAMTRACE CHRONOLOGICAL THREAT TIMELINE',
      '========================================',
      ...events.map(
        (ev, i) =>
          `[${ev.timeLabel}] ${ev.title} (${ev.isObserved ? 'OBSERVED IN OFFER' : 'PROJECTED ESCALATION'})\n` +
          `  - Tactic: ${ev.adversaryTactic}\n` +
          `  - Evidence: ${ev.evidence}\n` +
          `  - Immediate Countermeasure: ${ev.killChainAction}\n`
      ),
      '========================================',
      'Generated by SCAMTRACE Forensics Engine',
    ];
    navigator.clipboard.writeText(lines.join('\n'));
    setCopiedTimeline(true);
    setTimeout(() => setCopiedTimeline(false), 2000);
  };

  const handleCopyStageTips = (event: TimelineEvent) => {
    const text = [
      `PREVENTION TIPS FOR STAGE: ${event.title} (${event.timeLabel})`,
      '------------------------------------------------------------',
      ...(event.preventionTips || []).map((tip, idx) => `${idx + 1}. ${tip}`),
      '------------------------------------------------------------',
      `Immediate Kill-Chain Action: ${event.killChainAction}`,
      'Advisory by SCAMTRACE Forensics Engine',
    ].join('\n');

    navigator.clipboard.writeText(text);
    setCopiedTipsStageId(event.id);
    setTimeout(() => setCopiedTipsStageId(null), 2000);
  };

  const toggleMatrixStageTips = (stageId: string) => {
    setMatrixExpandedTips((prev) => ({
      ...prev,
      [stageId]: !prev[stageId],
    }));
  };

  if (!events || events.length === 0) {
    return null;
  }

  // Visual icons and semantic metadata for each attack stage
  const getStageMeta = (stage: TimelineEvent['stage'], customClass = 'w-4 h-4') => {
    switch (stage) {
      case 'trust':
        return {
          label: 'TRUST',
          name: 'Trust Establishment',
          icon: <UserCheck className={customClass} />,
          color: 'text-emerald-400',
          bg: 'bg-emerald-950/20',
          bgColor: 'bg-emerald-950/20',
          border: 'border-emerald-500/40',
          borderColor: 'border-emerald-500/40',
          badgeBg: 'bg-emerald-950/60 border-emerald-700/50 text-emerald-300',
          dot: 'bg-emerald-400',
          ring: 'ring-emerald-500/30',
        };
      case 'urgency':
        return {
          label: 'URGENCY',
          name: 'Manufactured Urgency',
          icon: <Clock className={customClass} />,
          color: 'text-amber-400',
          bg: 'bg-amber-950/20',
          bgColor: 'bg-amber-950/20',
          border: 'border-amber-500/40',
          borderColor: 'border-amber-500/40',
          badgeBg: 'bg-amber-950/60 border-amber-700/50 text-amber-300',
          dot: 'bg-amber-400',
          ring: 'ring-amber-500/30',
        };
      case 'financial':
        return {
          label: 'MONEY',
          name: 'Financial Extraction',
          icon: <CreditCard className={customClass} />,
          color: 'text-rose-400',
          bg: 'bg-rose-950/20',
          bgColor: 'bg-rose-950/20',
          border: 'border-rose-500/40',
          borderColor: 'border-rose-500/40',
          badgeBg: 'bg-rose-950/60 border-rose-700/50 text-rose-300',
          dot: 'bg-rose-400',
          ring: 'ring-rose-500/30',
        };
      case 'data':
        return {
          label: 'DATA',
          name: 'PII Exfiltration',
          icon: <FileSpreadsheet className={customClass} />,
          color: 'text-purple-400',
          bg: 'bg-purple-950/20',
          bgColor: 'bg-purple-950/20',
          border: 'border-purple-500/40',
          borderColor: 'border-purple-500/40',
          badgeBg: 'bg-purple-950/60 border-purple-700/50 text-purple-300',
          dot: 'bg-purple-400',
          ring: 'ring-purple-500/30',
        };
      case 'credential':
        return {
          label: 'CREDENTIAL',
          name: 'Credential Theft',
          icon: <Key className={customClass} />,
          color: 'text-violet-400',
          bg: 'bg-violet-950/20',
          bgColor: 'bg-violet-950/20',
          border: 'border-violet-500/40',
          borderColor: 'border-violet-500/40',
          badgeBg: 'bg-violet-950/60 border-violet-700/50 text-violet-300',
          dot: 'bg-violet-400',
          ring: 'ring-violet-500/30',
        };
      case 'extortion':
        return {
          label: 'EXTORTION',
          name: 'Threat Escalation',
          icon: <AlertOctagon className={customClass} />,
          color: 'text-red-400',
          bg: 'bg-red-950/20',
          bgColor: 'bg-red-950/20',
          border: 'border-red-500/40',
          borderColor: 'border-red-500/40',
          badgeBg: 'bg-red-950/60 border-red-700/50 text-red-300',
          dot: 'bg-red-400',
          ring: 'ring-red-500/30',
        };
      case 'isolation':
        return {
          label: 'ISOLATION',
          name: 'Victim Isolation',
          icon: <ShieldAlert className={customClass} />,
          color: 'text-orange-400',
          bg: 'bg-orange-950/20',
          bgColor: 'bg-orange-950/20',
          border: 'border-orange-500/40',
          borderColor: 'border-orange-500/40',
          badgeBg: 'bg-orange-950/60 border-orange-700/50 text-orange-300',
          dot: 'bg-orange-400',
          ring: 'ring-orange-500/30',
        };
      case 'other':
      default:
        return {
          label: 'CUTOFF',
          name: 'Resale & Ghosting',
          icon: <UserX className={customClass} />,
          color: 'text-slate-400',
          bg: 'bg-slate-900/60',
          bgColor: 'bg-slate-900/60',
          border: 'border-slate-700/60',
          borderColor: 'border-slate-700/60',
          badgeBg: 'bg-slate-900 border-slate-700 text-slate-300',
          dot: 'bg-slate-400',
          ring: 'ring-slate-600/30',
        };
    }
  };

  const getStageAccent = (ev: TimelineEvent) => {
    return getStageMeta(ev.stage);
  };

  const activeAccent = getStageAccent(activeEvent);

  return (
    <div id="scam-timeline-section" className="w-full max-w-4xl mx-auto px-4 mb-8">
      {/* Section Header with Actions */}
      <div className="mb-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg bg-cyan-950/60 border border-cyan-500/30 flex items-center justify-center text-cyan-400">
            <Clock className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white tracking-tight">
                Scam Timeline
              </h3>
              <span className="text-[11px] font-mono text-cyan-400 px-1.5 py-0.5 rounded bg-cyan-950/40 border border-cyan-800/40">
                Chronological Projection
              </span>
            </div>
            <p className="text-xs text-slate-400">
              Interactive timeline mapping detected events and theoretical attack escalation
            </p>
          </div>
        </div>

        {/* Top Control Bar */}
        <div className="flex items-center gap-2 self-start sm:self-auto">
          {/* View Toggle (Interactive vs Matrix) */}
          <div className="flex items-center p-0.5 bg-slate-900 border border-slate-800 rounded-lg text-xs">
            <button
              type="button"
              onClick={() => setViewMode('interactive')}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                viewMode === 'interactive'
                  ? 'bg-cyan-950 text-cyan-300 border border-cyan-800/50'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Timeline View
            </button>
            <button
              type="button"
              onClick={() => setViewMode('matrix')}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                viewMode === 'matrix'
                  ? 'bg-cyan-950 text-cyan-300 border border-cyan-800/50'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Sequence Flow
            </button>
          </div>

          {/* Copy Report */}
          <button
            type="button"
            onClick={handleCopyTimelineSummary}
            className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg border border-slate-800 bg-slate-900 text-xs font-mono text-slate-300 hover:text-cyan-300 hover:border-slate-700 transition-colors"
            title="Copy Chronological Timeline"
          >
            {copiedTimeline ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-400" />
                <span className="text-[11px] text-emerald-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5" />
                <span className="text-[11px] hidden sm:inline">Export</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Main Container Card */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4 sm:p-5 shadow-xl backdrop-blur-sm">
        {/* Sub-header: Playback Controls & Filter Tabs */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 mb-4 border-b border-slate-800/70">
          {/* Simulation & Playback Controls */}
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={() => setIsPlaying(!isPlaying)}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium font-mono transition-all ${
                isPlaying
                  ? 'bg-amber-500/20 text-amber-300 border border-amber-500/40 hover:bg-amber-500/30'
                  : 'bg-cyan-500/10 text-cyan-300 border border-cyan-500/30 hover:bg-cyan-500/20 shadow-sm'
              }`}
            >
              {isPlaying ? (
                <>
                  <Pause className="w-3.5 h-3.5 fill-current" />
                  <span>Pause Simulation</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-current" />
                  <span>Auto-Simulate</span>
                </>
              )}
            </button>

            {/* Stepper buttons */}
            <div className="flex items-center bg-slate-950 border border-slate-800 rounded-lg p-0.5">
              <button
                type="button"
                onClick={handlePrev}
                disabled={selectedIndex === 0}
                className="p-1 rounded text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                title="Previous Milestone"
                aria-label="Previous milestone"
              >
                <ChevronLeft className="w-4 h-4" />
              </button>
              <span className="text-[11px] font-mono px-2 text-slate-400">
                {selectedIndex + 1}/{filteredEvents.length}
              </span>
              <button
                type="button"
                onClick={handleNext}
                disabled={selectedIndex === filteredEvents.length - 1}
                className="p-1 rounded text-slate-400 hover:text-slate-200 disabled:opacity-30 disabled:hover:text-slate-400 transition-colors"
                title="Next Milestone"
                aria-label="Next milestone"
              >
                <ChevronRight className="w-4 h-4" />
              </button>
            </div>

            {/* Speed Toggle */}
            <button
              type="button"
              onClick={() => setPlaybackSpeed(playbackSpeed === 1 ? 2 : 1)}
              className="px-2 py-1 rounded border border-slate-800 bg-slate-950 text-[11px] font-mono text-slate-400 hover:text-slate-200 transition-colors"
              title="Toggle Playback Speed"
            >
              {playbackSpeed}x
            </button>

            {/* Reset */}
            <button
              type="button"
              onClick={handleResetPlayback}
              className="p-1.5 rounded border border-slate-800 bg-slate-950 text-slate-400 hover:text-slate-200 transition-colors"
              title="Reset to Beginning"
              aria-label="Reset simulation"
            >
              <RotateCcw className="w-3.5 h-3.5" />
            </button>
          </div>

          {/* Filter Pills (All / Observed / Projected) */}
          <div className="flex items-center p-0.5 bg-slate-950 border border-slate-800 rounded-lg text-xs self-start sm:self-auto">
            <button
              type="button"
              onClick={() => {
                setFilterMode('all');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'all'
                  ? 'bg-slate-800 text-white shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              All Events ({events.length})
            </button>
            <button
              type="button"
              onClick={() => {
                setFilterMode('observed');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'observed'
                  ? 'bg-emerald-950/80 text-emerald-300 border border-emerald-800/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Observed ({events.filter((e) => e.isObserved).length})
            </button>
            <button
              type="button"
              onClick={() => {
                setFilterMode('projected');
                setSelectedIndex(0);
              }}
              className={`px-2.5 py-1 rounded font-medium transition-colors ${
                filterMode === 'projected'
                  ? 'bg-cyan-950/80 text-cyan-300 border border-cyan-800/40 shadow-sm'
                  : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              Projected ({events.filter((e) => !e.isObserved).length})
            </button>
          </div>
        </div>

        {/* View Mode 1: Interactive Timeline Track & Inspector Card */}
        {viewMode === 'interactive' && (
          <div>
            {/* Interactive Chronological Spine / Node Scrubber */}
            <div className="relative pt-6 pb-8 px-2 overflow-x-auto">
              {/* Horizontal Line background */}
              <div className="absolute top-10 left-6 right-6 h-0.5 bg-slate-800 -translate-y-1/2" />

              {/* Dynamic filled line up to active node */}
              {filteredEvents.length > 1 && (
                <div
                  className="absolute top-10 left-6 h-0.5 bg-gradient-to-r from-cyan-500 via-amber-500 to-rose-500 -translate-y-1/2 transition-all duration-300"
                  style={{
                    width: `calc(${(selectedIndex / (filteredEvents.length - 1)) * 100}% - 24px)`,
                  }}
                />
              )}

              {/* Node Points along the spine */}
              <div className="relative flex items-center justify-between min-w-[560px]">
                {filteredEvents.map((ev, idx) => {
                  const isSelected = idx === selectedIndex;
                  const isCurrentPosition = ev.id === events[currentEventIndex]?.id;
                  const isInterventionLine = idx === interventionIndex;
                  const accent = getStageAccent(ev);

                  return (
                    <div key={ev.id} className="flex flex-col items-center group relative">
                      {/* "You Are Here" Marker */}
                      {isCurrentPosition && (
                        <div className="absolute -top-7 flex flex-col items-center animate-bounce">
                          <span className="text-[10px] font-mono font-bold text-amber-400 px-1.5 py-0.2 rounded bg-amber-950 border border-amber-800/60 whitespace-nowrap shadow-sm">
                            YOU ARE HERE
                          </span>
                          <div className="w-1.5 h-1.5 bg-amber-400 rotate-45 -mt-0.5" />
                        </div>
                      )}

                      {/* Node Button with Visual Stage Icon */}
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedIndex(idx);
                          setIsPlaying(false);
                          setIsPreventionTipsExpanded(true);
                        }}
                        className={`w-9 h-9 sm:w-10 sm:h-10 rounded-xl flex items-center justify-center transition-all cursor-pointer relative z-10 ${
                          isSelected
                            ? `bg-slate-950 border-2 ${accent.borderColor} ring-4 ${accent.ring} scale-110 shadow-lg shadow-cyan-950/50`
                            : 'bg-slate-900 border border-slate-700/80 hover:border-slate-500 hover:scale-105'
                        }`}
                        title={`Click to view ${ev.timeLabel} · ${accent.label} (${ev.title}) prevention tips`}
                      >
                        <span
                          className={`transition-colors ${
                            isSelected
                              ? accent.color
                              : ev.isObserved
                              ? `${accent.color} opacity-90`
                              : 'text-slate-400 group-hover:text-slate-200'
                          }`}
                        >
                          {accent.icon}
                        </span>

                        {/* Observed Indicator Dot on Top-Right */}
                        {ev.isObserved && (
                          <span
                            className="absolute -top-1 -right-1 w-2.5 h-2.5 rounded-full bg-emerald-400 border-2 border-slate-950 shadow-sm"
                            title="Directly Observed in Uploaded Offer"
                          />
                        )}
                      </button>

                      {/* Time Marker & Stage Label */}
                      <button
                        type="button"
                        onClick={() => {
                          setSelectedIndex(idx);
                          setIsPlaying(false);
                          setIsPreventionTipsExpanded(true);
                        }}
                        className="mt-2 text-center cursor-pointer group-hover:opacity-100 focus:outline-none flex flex-col items-center"
                        title={`Click to view ${ev.timeLabel} (${accent.label}) prevention tips`}
                      >
                        <span
                          className={`block text-[11px] font-mono font-bold ${
                            isSelected ? 'text-cyan-300' : 'text-slate-300 group-hover:text-white'
                          }`}
                        >
                          {ev.timeLabel}
                        </span>
                        <span
                          className={`inline-block text-[9px] font-mono font-bold tracking-wider px-1 py-0.2 rounded uppercase mt-0.5 ${
                            isSelected
                              ? `${accent.color} bg-slate-950 border ${accent.borderColor}`
                              : 'text-slate-400'
                          }`}
                        >
                          {accent.label}
                        </span>
                        <span
                          className={`block text-[10px] max-w-[85px] truncate leading-tight mt-0.5 ${
                            isSelected ? 'text-slate-200 font-semibold' : 'text-slate-400 group-hover:text-slate-300'
                          }`}
                        >
                          {ev.title}
                        </span>
                      </button>

                      {/* Intervention Cut-off Line Indicator */}
                      {isInterventionLine && (
                        <div
                          className="absolute -bottom-5 text-[9px] font-mono text-rose-400 whitespace-nowrap"
                          title="Point of No Return: Cease all actions before this milestone"
                        >
                          ⚠ Critical Cut-Off
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Active Milestone Forensic Detail Card */}
            <div
              className={`rounded-xl border ${activeAccent.border} ${activeAccent.bg} p-4 sm:p-6 transition-all duration-300 mt-2`}
            >
              {/* Card Header */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 pb-3 border-b border-slate-800/80">
                <div className="flex items-start sm:items-center gap-3.5">
                  <div
                    className={`w-11 h-11 rounded-xl flex items-center justify-center shrink-0 border ${activeAccent.borderColor} ${activeAccent.bgColor} ${activeAccent.color} shadow-lg`}
                  >
                    {getStageMeta(activeEvent.stage, 'w-6 h-6').icon}
                  </div>
                  <div>
                    <div className="flex flex-wrap items-center gap-2 mb-1">
                      <span className="text-xs font-mono font-bold tracking-wider text-cyan-400">
                        {activeEvent.timeframe}
                      </span>
                      <span className="text-slate-600">·</span>
                      <span
                        className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border flex items-center gap-1.5 ${activeAccent.badgeBg}`}
                      >
                        {getStageMeta(activeEvent.stage, 'w-3 h-3').icon}
                        <span>{activeAccent.label} · {activeAccent.name}</span>
                      </span>
                      <span className="text-slate-600">·</span>
                      <span
                        className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded border ${
                          activeEvent.isObserved
                            ? 'bg-emerald-950/60 text-emerald-300 border-emerald-700/50'
                            : 'bg-slate-900 text-slate-400 border-slate-700/60'
                        }`}
                      >
                        {activeEvent.isObserved ? 'OBSERVED IN OFFER' : 'PROJECTED THREAT'}
                      </span>
                    </div>
                    <h4 className="text-base sm:text-lg font-bold text-white tracking-tight">
                      {activeEvent.title}
                    </h4>
                  </div>
                </div>

                {/* Action buttons: Toggle Prevention Tips & Jump to 'You Are Here' */}
                <div className="flex items-center gap-2 self-start sm:self-auto">
                  <button
                    type="button"
                    onClick={() => setIsPreventionTipsExpanded(!isPreventionTipsExpanded)}
                    className="flex items-center gap-1.5 text-xs font-mono text-emerald-300 hover:text-emerald-200 px-2.5 py-1 rounded bg-emerald-950/60 border border-emerald-700/50 transition-colors shadow-sm"
                    title="Toggle Prevention Tips for this Phase"
                  >
                    <ShieldCheck className="w-3.5 h-3.5 text-emerald-400" />
                    <span>{isPreventionTipsExpanded ? 'Hide Prevention Tips' : 'Prevention Tips (4)'}</span>
                  </button>

                  {events[currentEventIndex] && activeEvent.id !== events[currentEventIndex]?.id && (
                    <button
                      type="button"
                      onClick={handleJumpToCurrent}
                      className="text-xs font-mono text-amber-300 hover:text-amber-200 px-2.5 py-1 rounded bg-amber-950/40 border border-amber-800/50 transition-colors"
                    >
                      Jump to Current →
                    </button>
                  )}
                </div>
              </div>

              {/* 4-Quadrant Information Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 my-4">
                {/* Quadrant 1: Evidence / Verbatim Text */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                      <FileSearch className="w-3.5 h-3.5 text-cyan-400" />
                      <span>Observed Artifact & Signal</span>
                    </span>
                    {activeEvent.isObserved && (
                      <span className="text-[10px] font-mono text-emerald-400 bg-emerald-950/40 px-1.5 py-0.5 rounded border border-emerald-800/40">
                        Direct Evidence
                      </span>
                    )}
                  </div>
                  <div className="text-xs font-mono text-slate-300 bg-slate-900/90 rounded p-2.5 border border-slate-800/60 italic leading-relaxed">
                    "{activeEvent.evidence}"
                  </div>
                  <p className="text-xs text-slate-400 mt-2 leading-relaxed">
                    {activeEvent.explanation}
                  </p>
                </div>

                {/* Quadrant 2: Adversary Playbook & Tactic */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <Zap className="w-3.5 h-3.5 text-amber-400" />
                    <span className="text-xs font-semibold text-slate-300">
                      Adversary Playbook & Tactic
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed mb-3">
                    {activeEvent.adversaryTactic}
                  </p>
                  <div className="pt-2 border-t border-slate-800/60">
                    <span className="text-[11px] font-mono text-slate-400 block mb-0.5">
                      Psychological Lever:
                    </span>
                    <span className="text-xs font-medium text-amber-300/90">
                      {activeEvent.psychologicalLever}
                    </span>
                  </div>
                </div>

                {/* Quadrant 3: Potential Victim Exposure */}
                <div className="rounded-lg bg-slate-950/80 border border-slate-800/80 p-3.5">
                  <div className="flex items-center gap-1.5 mb-2">
                    <AlertTriangle className="w-3.5 h-3.5 text-rose-400" />
                    <span className="text-xs font-semibold text-slate-300">
                      Victim Impact at this Milestone
                    </span>
                  </div>
                  <p className="text-xs text-slate-300 leading-relaxed mb-2">
                    {activeEvent.potentialVictimImpact}
                  </p>
                  <div className="text-[11px] font-mono text-rose-300/80 bg-rose-950/30 p-2 rounded border border-rose-900/40">
                    <span className="font-semibold text-rose-400">If ignored: </span>
                    {activeEvent.consequenceIfIgnored}
                  </div>
                </div>

                {/* Quadrant 4: Immediate Kill-Chain Countermeasure */}
                <div className="rounded-lg bg-cyan-950/40 border border-cyan-800/50 p-3.5 flex flex-col justify-between">
                  <div>
                    <div className="flex items-center gap-1.5 mb-2">
                      <ShieldAlert className="w-3.5 h-3.5 text-cyan-400" />
                      <span className="text-xs font-bold text-cyan-300 uppercase tracking-wide">
                        Kill-Chain Break Window
                      </span>
                    </div>
                    <p className="text-xs font-medium text-cyan-100 leading-relaxed">
                      {activeEvent.killChainAction}
                    </p>
                  </div>
                  <div className="mt-3 pt-2 border-t border-cyan-800/40 flex items-center justify-between text-[11px] font-mono text-cyan-300/80">
                    <span>Defuse Risk:</span>
                    <span className="text-emerald-400 font-bold">100% Effective</span>
                  </div>
                </div>
              </div>

              {/* Expandable Phase-Specific Prevention Tips */}
              <div className="mt-4 pt-3 border-t border-slate-800/80">
                <div className="rounded-xl border border-emerald-900/50 bg-emerald-950/20 overflow-hidden shadow-inner">
                  <button
                    type="button"
                    onClick={() => setIsPreventionTipsExpanded(!isPreventionTipsExpanded)}
                    className="w-full flex items-center justify-between p-3.5 hover:bg-emerald-950/30 transition-colors text-left"
                    aria-expanded={isPreventionTipsExpanded}
                  >
                    <div className="flex items-center gap-2.5">
                      <div className="w-7 h-7 rounded-lg bg-emerald-900/60 border border-emerald-700/50 flex items-center justify-center text-emerald-400">
                        <ShieldCheck className="w-4 h-4" />
                      </div>
                      <div>
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="text-xs font-bold text-emerald-300">
                            Prevention Tips: {activeEvent.title}
                          </span>
                          <span className={`text-[10px] font-mono font-bold px-1.5 py-0.5 rounded border flex items-center gap-1 ${activeAccent.badgeBg}`}>
                            {getStageMeta(activeEvent.stage, 'w-3 h-3').icon}
                            <span>{activeAccent.label}</span>
                          </span>
                          <span className="text-[10px] font-mono text-emerald-400 px-1.5 py-0.5 rounded bg-emerald-900/50 border border-emerald-700/40">
                            {activeEvent.preventionTips?.length || 4} Defensive Steps
                          </span>
                        </div>
                        <span className="text-[11px] text-slate-400 block mt-0.5">
                          {isPreventionTipsExpanded
                            ? 'Click to collapse prevention guidance'
                            : 'Click to expand actionable defense steps for this specific phase'}
                        </span>
                      </div>
                    </div>
                    <div className="flex items-center gap-2 text-emerald-400 text-xs font-mono">
                      <span className="hidden sm:inline">
                        {isPreventionTipsExpanded ? 'Collapse' : 'Expand'}
                      </span>
                      {isPreventionTipsExpanded ? (
                        <ChevronUp className="w-4 h-4" />
                      ) : (
                        <ChevronDown className="w-4 h-4" />
                      )}
                    </div>
                  </button>

                  {isPreventionTipsExpanded && (
                    <div className="p-4 pt-1 border-t border-emerald-900/30 space-y-3">
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-2">
                        {activeEvent.preventionTips?.map((tip, tipIdx) => {
                          const [title, ...description] = tip.split(': ');
                          return (
                            <div
                              key={tipIdx}
                              className="rounded-lg bg-slate-950/90 border border-emerald-900/40 p-3 flex items-start gap-2.5 text-xs text-slate-300"
                            >
                              <div className="w-5 h-5 rounded-full bg-emerald-950 border border-emerald-700/60 flex items-center justify-center shrink-0 mt-0.5 text-emerald-400 text-[10px] font-mono font-bold">
                                {tipIdx + 1}
                              </div>
                              <div className="leading-relaxed">
                                {description.length > 0 ? (
                                  <>
                                    <strong className="text-emerald-300 font-semibold block mb-0.5">
                                      {title}:
                                    </strong>
                                    <span className="text-slate-300">{description.join(': ')}</span>
                                  </>
                                ) : (
                                  <span>{tip}</span>
                                )}
                              </div>
                            </div>
                          );
                        })}
                      </div>

                      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pt-2 border-t border-emerald-900/30 text-[11px] font-mono text-slate-400">
                        <span>
                          Applied timeframe: <strong className="text-white">{activeEvent.timeLabel} ({activeEvent.timeframe})</strong>
                        </span>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleCopyStageTips(activeEvent);
                          }}
                          className="flex items-center gap-1.5 text-emerald-400 hover:text-emerald-300 transition-colors self-start sm:self-auto"
                        >
                          {copiedTipsStageId === activeEvent.id ? (
                            <>
                              <Check className="w-3.5 h-3.5 text-emerald-400" />
                              <span className="text-emerald-300">Phase Tips Copied!</span>
                            </>
                          ) : (
                            <>
                              <Copy className="w-3.5 h-3.5" />
                              <span>Copy Phase Defense Tips</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Interactive "What-If" Scenario Branching */}
              <div className="mt-4 pt-3 border-t border-slate-800/70">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-2">
                  <span className="text-xs font-mono font-bold text-slate-300 flex items-center gap-1.5">
                    <span>What-If Tactical Branching:</span>
                  </span>
                  <div className="flex items-center p-0.5 bg-slate-950 border border-slate-800 rounded-md text-xs self-start sm:self-auto">
                    <button
                      type="button"
                      onClick={() => setScenarioMode('intervene')}
                      className={`px-2.5 py-1 rounded font-medium transition-colors ${
                        scenarioMode === 'intervene'
                          ? 'bg-emerald-950 text-emerald-300 border border-emerald-700/50'
                          : 'text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      Branch A: Candidate Intervenes (Safe)
                    </button>
                    <button
                      type="button"
                      onClick={() => setScenarioMode('comply')}
                      className={`px-2.5 py-1 rounded font-medium transition-colors ${
                        scenarioMode === 'comply'
                          ? 'bg-rose-950 text-rose-300 border border-rose-700/50'
                          : 'text-slate-400 hover:text-slate-200'
                      }`}
                    >
                      Branch B: Candidate Complies (Loss)
                    </button>
                  </div>
                </div>

                <div
                  className={`rounded-lg p-3 text-xs leading-relaxed border ${
                    scenarioMode === 'intervene'
                      ? 'bg-emerald-950/20 border-emerald-800/40 text-emerald-200'
                      : 'bg-rose-950/20 border-rose-800/40 text-rose-200'
                  }`}
                >
                  {scenarioMode === 'intervene' ? (
                    <div className="flex items-start gap-2">
                      <ShieldCheck className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-emerald-300 block mb-0.5">
                          Protective Outcome:
                        </strong>
                        When you request independent confirmation through the official corporate
                        directory or refuse upfront payment, the adversary fails. They will either
                        evade live verification, terminate the chat, or reveal conflicting domains.
                        Your financial loss and identity exposure remain $0.
                      </div>
                    </div>
                  ) : (
                    <div className="flex items-start gap-2">
                      <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-rose-300 block mb-0.5">
                          Adversary Escalation Trajectory:
                        </strong>
                        Complying at {activeEvent.timeLabel} signals to the scam syndicate that you
                        are a receptive target. They proceed immediately to the next phase (
                        {events[Math.min(selectedIndex + 1, events.length - 1)]?.title}), demanding
                        secondary verification deposits or harvesting banking credentials.
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* View Mode 2: Full Sequence Matrix / Flow Grid */}
        {viewMode === 'matrix' && (
          <div className="space-y-3 pt-2">
            <div className="text-xs text-slate-400 mb-2 flex items-center justify-between">
              <span>Full chronological trajectory from initial hook to post-incident exploitation:</span>
              <span className="font-mono text-cyan-400">Total Milestones: {filteredEvents.length}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {filteredEvents.map((ev, idx) => {
                const accent = getStageAccent(ev);
                const isCurrentPosition = ev.id === events[currentEventIndex]?.id;

                return (
                  <div
                    key={ev.id}
                    className={`rounded-xl border p-4 transition-all ${
                      isCurrentPosition
                        ? 'border-amber-500/50 bg-amber-950/10 ring-2 ring-amber-500/20'
                        : 'border-slate-800 bg-slate-950/60 hover:border-slate-700'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-2.5">
                      <div className="flex items-center gap-2.5">
                        <div
                          className={`w-8 h-8 rounded-lg flex items-center justify-center border ${accent.borderColor} ${accent.bgColor} ${accent.color} shadow-sm shrink-0`}
                        >
                          {accent.icon}
                        </div>
                        <div>
                          <div className="flex items-center gap-1.5">
                            <span className="text-xs font-mono font-bold text-cyan-400">
                              {ev.timeLabel}
                            </span>
                            <span className="text-slate-600">·</span>
                            <span className={`text-[10px] font-mono font-bold uppercase ${accent.color}`}>
                              {accent.label}
                            </span>
                          </div>
                          <span className="text-[10px] font-mono text-slate-400 block -mt-0.5">
                            {ev.timeframe}
                          </span>
                        </div>
                      </div>
                      <span
                        className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
                          ev.isObserved
                            ? 'bg-emerald-950/60 text-emerald-300 border-emerald-800/40'
                            : 'bg-slate-900 text-slate-400 border-slate-800'
                        }`}
                      >
                        {ev.isObserved ? 'OBSERVED' : 'PROJECTED'}
                      </span>
                    </div>

                    <h4 className="text-sm font-semibold text-white mb-2">{ev.title}</h4>

                    <div className="p-2 rounded bg-slate-900/80 border border-slate-800/60 text-xs font-mono text-slate-300 italic mb-2 line-clamp-2">
                      "{ev.evidence}"
                    </div>

                    <p className="text-xs text-slate-400 mb-2.5 line-clamp-2">
                      {ev.explanation}
                    </p>

                    <div className="pt-2 border-t border-slate-800/60 flex items-center justify-between text-[11px]">
                      <span className="text-slate-400 font-mono">Countermeasure:</span>
                      <span className="text-cyan-300 font-medium truncate max-w-[200px]" title={ev.killChainAction}>
                        {ev.killChainAction}
                      </span>
                    </div>

                    {/* Expandable Phase Prevention Tips in Matrix View */}
                    <div className="pt-2 mt-2 border-t border-slate-800/60">
                      <button
                        type="button"
                        onClick={() => toggleMatrixStageTips(ev.id)}
                        className="w-full flex items-center justify-between text-xs font-mono text-emerald-400 hover:text-emerald-300 py-1 transition-colors group"
                      >
                        <span className="flex items-center gap-1.5 font-semibold">
                          <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 group-hover:scale-110 transition-transform" />
                          <span>
                            {matrixExpandedTips[ev.id]
                              ? 'Hide Prevention Tips'
                              : `View Prevention Tips (${ev.preventionTips?.length || 4})`}
                          </span>
                        </span>
                        <div className="flex items-center gap-1 text-[11px]">
                          <span className="text-slate-500">
                            {matrixExpandedTips[ev.id] ? 'Close' : 'Expand'}
                          </span>
                          {matrixExpandedTips[ev.id] ? (
                            <ChevronUp className="w-3.5 h-3.5" />
                          ) : (
                            <ChevronDown className="w-3.5 h-3.5" />
                          )}
                        </div>
                      </button>

                      {matrixExpandedTips[ev.id] && (
                        <div className="mt-2 pt-2 border-t border-emerald-900/40 space-y-2 bg-slate-950/80 rounded-lg p-3 border border-emerald-900/30">
                          <div className="flex items-center justify-between text-[11px] font-mono text-emerald-300 font-bold mb-1">
                            <span>Defensive Protocol for {ev.timeLabel}:</span>
                            <button
                              type="button"
                              onClick={(e) => {
                                e.stopPropagation();
                                handleCopyStageTips(ev);
                              }}
                              className="text-[10px] text-slate-400 hover:text-emerald-300 flex items-center gap-1"
                            >
                              <Copy className="w-3 h-3" />
                              <span>Copy</span>
                            </button>
                          </div>
                          {ev.preventionTips?.map((tip, tIdx) => {
                            const [head, ...body] = tip.split(': ');
                            return (
                              <div key={tIdx} className="flex items-start gap-2 text-xs text-slate-300 leading-snug">
                                <span className="w-4 h-4 rounded-full bg-emerald-950 border border-emerald-800/60 flex items-center justify-center shrink-0 mt-0.5 text-emerald-400 text-[10px] font-mono">
                                  {tIdx + 1}
                                </span>
                                <div>
                                  {body.length > 0 ? (
                                    <>
                                      <strong className="text-emerald-300 font-semibold">{head}: </strong>
                                      <span>{body.join(': ')}</span>
                                    </>
                                  ) : (
                                    <span>{tip}</span>
                                  )}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
